# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
language: R
services:
- docker
cache: packages
before_install:
- svn checkout https://github.com/SeleniumHQ/selenium/trunk/common/src/web
- docker run -d -p 3000:8080 --name http-server -v $(pwd)/web:/public redsadic/docker-http-server
- docker run -d -p 127.0.0.1:4444:4444 -v /dev/shm:/dev/shm --link http-server selenium/standalone-chrome:2.53.1
script:
  - ls
